//! ZigOQS — safe Zig wrapper around liboqs.
const init = @import("init.zig");

pub const ensureInitialized = init.ensure;
pub const OqsError = @import("errors.zig").OqsError;

pub const Kem = @import("kem.zig").Kem;
pub const Sig = @import("sig.zig").Sig;

// Comptime-typed, ergonomic layer over the runtime cores. `kem`/`sig` are
// namespaces of per-algorithm wrappers (e.g. `oqs.kem.MlKem768`), generated by
// tools/gen-manifest.sh into algorithms.zig.
const algorithms = @import("algorithms.zig");
pub const kem = algorithms.kem;
pub const sig = algorithms.sig;
pub const SharedSecret = @import("keys.zig").SharedSecret;

// Raw liboqs C symbols (e.g. for the registry gate's enabled-count checks).
pub const c = @import("c.zig").c;

pub const testing = struct {
    pub const seedKat = @import("rng.zig").seedKat;
};

pub const version = "0.0.0";

test {
    _ = init;
    _ = @import("rng.zig");
    _ = @import("kem.zig");
    _ = @import("sig.zig");
    _ = @import("keys.zig");
    _ = @import("typed.zig");
    _ = algorithms;
}
