// SPDX-License-Identifier: MIT
// GENERATED by tools/gen-manifest.sh from liboqs 0.15.0. Do not edit by hand.
// Portable-only build configuration for ZigOQS, scoped to the families that
// build.zig currently compiles (build/enabled-families.txt, the single source
// of truth this generator reads). This MUST stay in sync with that list: the
// kem/sig dispatchers (kem.c/sig.c) reference OQS_*_<alg>_new() under these
// OQS_ENABLE_* guards, and kem.h/sig.h #include the per-family umbrella headers
// under the family-level guards. Enabling a family here without compiling it
// (or vice versa) breaks the build.
// UOV (needs OpenSSL), stateful signatures, and optimized backends excluded.

#ifndef OQS_OQSCONFIG_H
#define OQS_OQSCONFIG_H

// --- Version ---
#define OQS_VERSION_TEXT "0.15.0"
#define OQS_VERSION_MAJOR 0
#define OQS_VERSION_MINOR 15
#define OQS_VERSION_PATCH 0

// --- Build target / system ---
#define OQS_COMPILE_BUILD_TARGET "generic"
#define OQS_DIST_BUILD 1
#define OQS_BUILD_ONLY_LIB 1

// --- System feature flags ---
#define OQS_HAVE_POSIX_MEMALIGN 1

// --- No GPU/CUPQC/ICICLE/libjade ---
#define OQS_USE_CUPQC 0
#define OQS_USE_ICICLE 0
#define OQS_LIBJADE_BUILD 0

// --- KEMs ---
#define OQS_ENABLE_KEM_HQC 1
#define OQS_ENABLE_KEM_ML_KEM 1
#define OQS_ENABLE_KEM_hqc_128 1
#define OQS_ENABLE_KEM_hqc_192 1
#define OQS_ENABLE_KEM_hqc_256 1
#define OQS_ENABLE_KEM_ml_kem_1024 1
#define OQS_ENABLE_KEM_ml_kem_512 1
#define OQS_ENABLE_KEM_ml_kem_768 1

// --- SIGs ---
#define OQS_ENABLE_SIG_FALCON 1
#define OQS_ENABLE_SIG_MAYO 1
#define OQS_ENABLE_SIG_ML_DSA 1
#define OQS_ENABLE_SIG_falcon_1024 1
#define OQS_ENABLE_SIG_falcon_512 1
#define OQS_ENABLE_SIG_falcon_padded_1024 1
#define OQS_ENABLE_SIG_falcon_padded_512 1
#define OQS_ENABLE_SIG_mayo_1 1
#define OQS_ENABLE_SIG_mayo_2 1
#define OQS_ENABLE_SIG_mayo_3 1
#define OQS_ENABLE_SIG_mayo_5 1
#define OQS_ENABLE_SIG_ml_dsa_44 1
#define OQS_ENABLE_SIG_ml_dsa_65 1
#define OQS_ENABLE_SIG_ml_dsa_87 1

// Families not listed in build/enabled-families.txt, plus UOV (requires
// OpenSSL) and stateful signatures (XMSS/LMS), are intentionally left
// undefined until they are compiled.

#endif // OQS_OQSCONFIG_H
